apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
status: {}
