apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: kafka-cluster
  labels:
    app: kafka-broker-1
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: kafka-cluster
  labels:
    app: kafka-broker-2
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker-2
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  namespace: kafka-cluster
  labels:
    app: kafka-broker-3
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker-3