apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: atlan-message-nodejs
  name: atlan-message-nodejs
spec:
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  selector:
    app: atlan-message-nodejs
status: {}
