apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: atlan-sheets-nodejs
  name: atlan-sheets-nodejs
spec:
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: atlan-sheets-nodejs
status: {}
