apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: atlan-nodejs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atlan-nodejs
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
status: {}
