apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: fluentd-container-log
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
